export const header: string;
export const content: string;
export const breadcrumb: string;
export const sidebar: string;
export const avatarContainer: string;
export const caption: string;
export const avatar: string;
export const devider: string;
export const footer: string;
