/**
 * ORGANIZATIONS
 */

export const REQUEST_ORGANIZATIONS = 'REQUEST_ORGANIZATIONS';
export const RECEIVE_ORGANIZATIONS = 'RECEIVE_ORGANIZATIONS';

/**
 * PAGES
 */

export const REQUEST_PAGES = 'REQUEST_PAGES';
export const RECEIVE_PAGES = 'RECEIVE_PAGES';

export const REQUEST_CREATE_PAGE = 'REQUEST_CREATE_PAGE';
export const RECEIVE_CREATE_PAGE = 'RECEIVE_CREATE_PAGE';

export const REQUEST_UPDATE_PAGE = 'REQUEST_UPDATE_PAGE';
export const RECEIVE_UPDATE_PAGE = 'RECEIVE_UPDATE_PAGE';

export const REQUEST_DELETE_PAGE = 'REQUEST_DELETE_PAGE';
export const RECEIVE_DELETE_PAGE = 'RECEIVE_DELETE_PAGE';

/**
 * COURSES 
 */

export const REQUEST_COURSES = 'REQUEST_COURSES';
export const RECEIVE_COURSES = 'RECEIVE_COURSES';
