/**
 * ORGANIZATIONS
 */

export const REQUEST_ORGANIZATIONS = 'REQUEST_ORGANIZATIONS';
export const RECEIVE_ORGANIZATIONS = 'RECEIVE_ORGANIZATIONS';

/**
 * PAGES
 */

export const REQUEST_PAGES = 'REQUEST_PAGES';
export const RECEIVE_PAGES = 'RECEIVE_PAGES';
