export const SET_CURRENT_USER = 'SET_CURRENT_USER';

/**
 * ORGANIZATION
 */

export const REQUEST_ORGANIZATION_EMPLOYERS = 'REQUEST_ORGANIZATION_EMPLOYERS';
export const RECEIVE_ORGANIZATION_EMPLOYERS = 'RECEIVE_ORGANIZATION_EMPLOYERS';
